server:
  port: 9091

spring:
  cloud:
    discovery:
      enabled: true
  main:
    allow-circular-references: true
  application:
    name: stock
  datasource:
    url: jdbc:mysql://localhost:3306/trendyol_stock?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: wtf1907.
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


